#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Independent Solar Energy Mesh System 
LUCI_DEPENDS:=+luci-app-statistics +luci-app-freifunk-widgets +collectd-mod-exec
LUCI_PKGARCH:=all
LUCI_TYPE:=app
LUCI_BASENAME:=luci

PKG_LICENSE:=Apache-2.0



include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
